# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: automation
name: application
version: 0.0.1
readme: README.md
authors:
  - cidrblock
description: Sample autoamtion application
license_file: LICENSE
tags:
  - application
repository: https://github.com/ansible-collections/automation-application
documentation: https://github.com/ansible-collections/automation-application
homepage: https://github.com/ansible-collections/automation-application
issues: https://github.com/ansible-collections/automation-application/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
