- hosts: h_group_1
  gather_facts: False
  tasks:
    - name: Set the fact
      ansible.builtin.set_fact:
        output:
          greeting: "Hello {{ first_name }} {{ last_name }}"
        cacheable: True
    - name: Greet the user
      ansible.builtin.debug:
        var: output.greeting
